---
- name: Check the global config of eltex switchs
#!!! Here need to enter group-hosts !!!
  hosts: hosts
#labstand_eltex
  gather_facts: false

  vars:
#    ansible_connection: ansible.netcommon.network_cli
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios

  tasks:
  - name: Get system info
    ansible.netcommon.cli_command:
      command: show system
    register: sh_sys

  - name: Check switch series
# Parse output system info
    set_fact:
      switch_model: "{{ sh_sys.stdout | parse_cli_textfsm('/ansible/sh_sys.textfsm') }}"
    failed_when:
#!!! Here need to enter all supported model !!!
    - switch_model[0]["Model"] != "2324" and
      switch_model[0]["Model"] != "2324P" and
      switch_model[0]["Model"] != "2348P" and
      switch_model[0]["Model"] != "2348B" and
      switch_model[0]["Model"] != "3324F"
#      switch_model[0]["Model"] != "3324" 

  - name: Get system info
    ansible.netcommon.cli_command:
      command: show ip interface
    register: sh_ip_int

  - name: Define mgmt vlan id
# Parse output version info
    set_fact:
      mgmt_vlan: "{{ sh_ip_int.stdout | parse_cli_textfsm('/ansible/vlan-id.textfsm') }}"
    failed_when: mgmt_vlan[0] is not defined

#  - name: Configure ntp
#    cisco.ios.ios_config:
#      lines:
#      - no sntp server 172.31.192.34
#      - no sntp server 172.31.192.53
#      - sntp client poll timer 180
#      - clock timezone MSK +3
#      - clock source sntp
#      - sntp source-interface vlan {{ mgmt_vlan[0]["Vlan_id"] }}
#      - sntp unicast client enable
#      - sntp server 172.31.172.15
#      - sntp server 172.31.172.30

  - name: Check aaa config
    ios_config:
      lines:
      - username mango password encrypted 74471672fef99014d9ba0def88853bbf6d28130f privilege 15
      - aaa authentication mode break
      - aaa authentication login authorization default tacacs local
      - aaa authentication enable authorization default tacacs enable
      - encrypted tacacs-server host 172.31.192.53 key ATm4PrBqj45nn7Km4Y33krbWremOvP53g8aCahwprsk=

  - name: Check snmp config
    ios_config:
      lines:
      - snmp-server server
      - no snmp-server location
      - snmp-server contact ***
      - encrypted snmp-server community caOijfcQ+GS/XvRv1bNi+7hyv8HZzoCcUCQ8mXRC+CA= ro 172.31.172.0 mask 255.255.255.0 view Default
      - encrypted snmp-server host 172.31.172.33 traps version 2c caOijfcQ+GS/XvRv1bNi+7hyv8HZzoCcUCQ8mXRC+CA=
      - no logging host 172.31.172.3
      - no logging host 172.31.192.34
      - no logging host 172.31.192.52
      - logging host 172.31.172.33
      - no logging console

  - name: Check access config
    ios_config:
      lines:
      - no ip http server
      - ip ssh server

  - name: Check telnet line config
    ios_config:
      parents: line telnet
      lines:
      - history size 190
      - exec-timeout 20

  - name: Check ssh line config
    ios_config:
      parents: line ssh
      lines:
      - history size 190
      - exec-timeout 20

  - name: Check loopback global config
    when: switch_model[0]["Model"] != "3324F"
    ios_config:
      lines:
      - loopback-detection enable

  - name: Save config
    register: write_out
    cisco.ios.ios_command:
      commands:
      - command: 'write'
        prompt: 'Overwrite file '
        answer: 'y'
#      wait_for:
#      - result[0] contains 'Copy succeeded'
    changed_when: write_out.stdout is search(".*Copy succeeded.*")
    failed_when: write_out.stdout is not search(".*Copy succeeded.*")
